config/routes.rb
Shapeseed::Application.routes.draw do
  
  resources :user_sessions
  resources :works, :only => [:create, :destroy, :show] do
    member do 
      get :tags
    end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :contributions
  resources :mentorships
  resources :searches
  resources :users do
    member do
      get :following, :followers, :mentors, :contributeds
    end
  end
  resources :people do
    member do
	  get :tags, :works, :mentees, :contributors
	end
  end

  root :to => 'pages#home'
  
  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/signup',    :to => 'users#new'
  match '/relations', :to => 'users#relations'
  match '/suggest',   :to => 'users#suggest'
  match '/contribute', :to => 'people#contribute'
  match 'logout', 	  :to => 'user_sessions#destroy', :as => :logout
  
  match '*path', 	  :to => 'pages#home'
  
  

end

app/models/user.rb
# == Schema Information
# Schema version: 20110403181559
#
# Table name: users
#
#  id         :integer         not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'

class User < ActiveRecord::Base

  #for authlogic
  acts_as_authentic
  
  attr_accessible :first, :last, :email, :password, :password_confirmation 
    
  #Normal Relationships among users ... follow, be followed
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id",
  								   :class_name => "Relationship",
  								   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  
  #Relationships with mentors. Follow a mentor. A mentor is followed
  has_many :mentorships, :foreign_key => "mentee_id", :dependent => :destroy
  has_many :mentors, :through => :mentorships, :source => :mentor
  
  #Contributions to mentors. You are again only following
  has_many :contributions, :foreign_key => "contributor_id", :dependent => :destroy
  has_many :contributeds, :through => :contributions, :source => :contributed
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :last,  	 :presence => true,
  						 :length => { :maximum => 25 }
  validates :first, 	 :presence => true,
  				   		 :length   => { :maximum => 25 }
  validates :email, 	 :presence => true,
  						 :uniqueness => { :case_sensitive => false }
  						 #:format   => { :with => email_regex },
  						 #:length => { :within => 6..100 }
  validates :password, 	 :presence => true,
  					     :confirmation => true
  					     #:length => { :within => 6..40 }
  
  #Relationship functions
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  #End
  
  #Contribution Functions
  def contribute!(contributed, work)
    contributions.create!(:contributed_id => contributed.id, :work_id => work.id)
  end
  
  def contribute?(contributed)
    contributions.find_by_contributed_id(contributed)
  end
  #End
  
  #Mentorship functions
  def mentee!(mentor)
    mentorships.create!(:mentor_id => mentor.id)
  end
  
  def unmentee!(mentor)
    mentorships.find_by_mentor_id(mentor).destroy
  end
  
  def mentoree?(mentor)
    mentorships.find_by_mentor_id(mentor)
  end 
  #End
  
  def name
    "#{@first_name} #{@last_name}"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :except => [:new, :create, :relations]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => [:edit, :update, :destroy]
  before_filter :require_no_user, :only => [:create, :new]
  
  def new
    @user = User.new
    @title = "Sign Up"
    @user_session = UserSession.new
    @search = Search.new
  end
  
  def show
    redirect_to(root_path) #in here right now because i dont want to make this part yet
    @user = User.find(params[:id])
    @title = "#{@user.first_name} #{@user.last_name}" 
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
	  #sign_in @user
	  #flash[:success] = "Welcome to ShapeSeed"
	  redirect_to root_path
    else
	  @title = "Sign Up"
	  @user.password = User.new.password
	  @user.password_confirmation = User.new.password_confirmation
	  redirect_to signup_path
    end
  end
  
  def update
    if @user.update_attributes(params[:user])
      #flash[:success] = "Profile updated"
      redirect_to @user
    else
      @title = "Edit User"
      render 'edit'
    end
  end
  
  def destroy 
    @user = User.find(params[:id])
    if !@user.admin?
      @user.destroy
      #flash[:success] = "User Removed."
    end
    redirect_to users_path
  end
  
  def relations
    @search = Search.new
    @user = current_user
    @title = "#{@user.first}"
    @mentors = @user.mentors
    @contributeds = @user.contributeds.index_by{|person| person[:id]}.values
    render 'show_relations'
  end
  
  def suggest
    @search = Search.new
    @title = "Suggest"
    @person = Person.new
    @user = current_user
    render 'suggest'
  end
  
  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_path) if !current_user.admin? || current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.text_field :first, :size => 37, :placeholder => "Your First Name" %>
  <br /> 
  <%= f.text_field :last, :size => 37, :placeholder => "Your Last Name" %>
  <br /> 
  <%= f.text_field :email, :size => 37, :placeholder => "Your Email" %>
  <br />
  <%= f.password_field :password, :size => 37, :placeholder => "Your Password" %>
  <br />
  <%= f.password_field :password_confirmation, :size => 37, :placeholder => "Confirm Password" %>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id),
             :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_mentor.html.erb
<%= form_for current_user.mentorships.build(:mentor_id => @person.id),
											:remote => true do |f| %>
  <div><%= f.hidden_field :mentor_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_mentor_form.html.erb
<div id="mentor_form">
  <% if current_user.mentoree?(@person) %>
    <%= render 'users/unmentor' %>
  <% else %>
    <%= render 'users/mentor' %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             :html => { :method => :delete },
             :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_unmentor.html.erb
<%= form_for current_user.mentorships.find_by_mentor_id(@person),
					:html => { :method => :delete },
					:remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user_display.html.erb
<% @user ||= current_user %>
  <% if !signed_in? %>
	<%= form_for(:user_session, :url => user_sessions_path) do |f| %>
	    <% f.error_messages %>
		  <%= f.text_field :email, :size => 22, :placeholder => "Email" %>
		  <%= f.password_field :password, :size => 22, :placeholder => "Password" %>
		  <%#= f.label :remember_me, "Auto!" %> <%#= f.check_box :remember_me %>
		  <%= f.submit "Log In" %>
		  <%= link_to "New? Sign Up", signup_path %>
  <% end %>
<% end %>

app/views/users/contribute.html.erb
<% if signed_in? %>

<%= form_for(@person) do |f| %>
  <%= render 'shared/error_messages', :f => f%>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first, :size => 37 %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last, :size => 37 %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 37 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, :size => 37 %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>  
  <div class="actions">
    <%= f.submit "Contribute" %>
  </div>
<% end %>


<% else %>

<%= render 'users/new' %>

<% end %>

app/views/users/new.html.erb
<div style="float:left; margin-left: 105px">
<h3>Sign Up</h3>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>
</div>

app/views/users/search.html.erb
<%= render 'shared/search_bar' %>

<% unless @search.empty? %>
  <div class="results">
    <%= render @search %>
  </div>
<% end %>

app/views/users/show.html.erb
<!--<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%#= @user.first_name %> <%= @user.last_name %>
      </h1>
      <%#= render 'follow_form' if signed_in? %>
    </td>
    <td class="sidebar round left">
      <%#= render 'shared/user_info' %>
      <%#= render 'shared/user_tags' %>
    </td>
  </tr>
  
</table>-->

<h1 style="text-align: center">
  <%= @user.first_name %> <%= @user.last_name %> <%= render 'follow_form' if signed_in? %>
</h1>
      

app/views/users/show_relations.html.erb
  <div id="relations_mentors">
    <h1>Following</h1>
    <% unless @mentors.empty? %>
      <% @mentors.each do |mentor| %>
        <a href="<%= person_path(mentor) %>"><h3><%= mentor.first %> <%= mentor.last %></h3></a>
      <% end %>
    <% end %>
  </div>
  
  <div id="relations_contributeds">
    <h1>Contributed</h1>
    <% unless @contributeds.empty? %>
      <% @contributeds.each do |contributed| %> 
        <a href="<%= person_path(contributed) %>"><h3><%= contributed.first %> <%= contributed.last %></h3></a>
      <% end %>
    <% end %>
  </div>
   

app/views/users/suggest.html.erb
<div id="suggest">
  <%= form_for(@person) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name, "Name the Person" %><br />
    <div style="float:left">
      <%= f.text_field :name, :size => 37%> 
    </div>
    <div class="suggesthelp"> 
      <p>Albert Einstein</p>
    </div>
  </div>
  <div class="field">
    <%= f.label :title, "Title their Role" %><br />
    <div style="float:left">
      <%= f.text_field :title, :size => 37%>
    </div>
    <div class="suggesthelp"> 
      <p>Father of Modern Physics</p>
    </div>
  </div>
  <div class="field">
    <%= f.label :description, "Detail their Accomplishments"%><br />
    <div style="float:left">
      <%= f.text_area :description, :size => "27x5", :wrap => "soft"%>
    </div>
    <div class="suggesthelp"> 
      <p>A renowned German born physicist who won the Nobel Prize for the discovery of the 
         photoelectric effect. Well-known for the Annus Mirabilis Papers, he also played a major 
         role in the Manhattan Project and famously denounced using nuclear fission as a weapon.
      </p>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Suggest" %>
  </div>
  <% end %>
</div>

<script>
//	$(document).ready(function(){
//		var names = <%= @peopleNames.to_json %>;
//		$("#nameInput").autocomplete(names);
//	});
</script>