config/routes.rb
Shapeseed::Application.routes.draw do
  
  resources :user_sessions
  resources :works, :only => [:create, :destroy, :show] do
    member do 
      get :tags
    end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :contributions
  resources :mentorships
  resources :searches
  resources :users do
    member do
      get :following, :followers, :mentors, :contributeds
    end
  end
  resources :people do
    member do
	  get :tags, :works, :mentees, :contributors
	end
  end

  root :to => 'pages#home'
  
  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/signup',    :to => 'users#new'
  match '/relations', :to => 'users#relations'
  match '/suggest',   :to => 'users#suggest'
  match '/contribute', :to => 'people#contribute'
  match 'logout', 	  :to => 'user_sessions#destroy', :as => :logout
  
  match '*path', 	  :to => 'pages#home'
  
  

end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :query, :min_age, :max_age, :work_results
  
  validates_numericality_of :min_age, :allow_nil => true, :greater_than_or_equal_to => 0, 
  									  :less_than_or_equal_to => 100, :only_integer => true,
  									  :message => "should be blank or an integer between 0 and 100"
  validates_numericality_of :max_age, :allow_nil => true, :greater_than_or_equal_to => 0, 
  									  :less_than_or_equal_to => 100, :only_integer => true,
  									  :message => "should be blank or an integer between 0 and 100"
  validates 				:query,   :presence => true
  
  def set_ages
	check_min
	check_max
	check_switch
    self.update_attributes(:min_age => @min_age, :max_age => @max_age)
  end
  
  def has_min_age?
    min_age.present?
  end
  
  def has_max_age?
    max_age.present?
  end
  
  def has_query?
    query.present?
  end
  
  def switch_ages?
    @max_age < @min_age
  end
  
  def save_results(results) 
    #save results here 
    self.update_attributes(:work_results => results)
  end
  
  private 
    def check_max
      if has_max_age?
        @max_age = max_age
      else
        @max_age = 100
      end
    end
    
    def check_min
      if has_min_age?
        @min_age = min_age
      else
        @min_age = 0
      end
    end
    
    def check_switch
      if switch_ages?
        @tmp = min_age
        @min_age = @max_age
        @max_age = @tmp
      end
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def create  
    @search = Search.new(params[:search])
	if @search.save
	  if params[:search][:query].blank?
	    flash[:notice] = "Please provide a query"
	    render 'index'
	  else
	    #*******
	    #This is for sunspot ... right now using acts_as_indexed to start
#         @results = Work.search do 
#           keywords params[:search][:query]
#           paginate(:page => params[:page], :per_page => 10)
#         end.results
	    #*******
	
	    #acts_as_indexed
	    @results = Work.find_with_index(params[:search][:query])
	  end
	  @search.set_ages
	  @results = @results.partition{|work| (work.age <= @search.max_age && 
	  										work.age >= @search.min_age)}[0]
	  @people_results = @results.map{|work| Person.find(work.person_id)}
	  @search.save_results(@results.map(&:id).join(" "))
      render 'search'
    else
      render 'index'
    end
  end
  
  def index
    @search = Search.new
    render 'index'
  end
  
end





#      @sunspot_search = Sunspot.search User, Tag, Work do |query| 
 #       query.keywords @search.query
  #      query.with(:age).greater_than @lower
   #     query.with(:age).less_than @upper
    #    query.paginate(:page => params[:page], :per_page => 10)
     # end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_bar.html.erb
<div id="search">
  <%= form_for(@search) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
	  <div class="fieldbar round left">
    	<%= f.text_field :query, :placeholder => " Search ShapeSeed: ", :size => 20 %>
    	<%= f.text_field :min_age, :placeholder => " Between Age: ", :size => 20 %>
    	<%= f.text_field :max_age, :placeholder => " And Age: ", :size => 20 %>
        <%= f.submit "Search" %>
      </div>
  <% end %>
</div>

app/views/searches/index.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td><%= render 'search_bar' %></td>
      <td id="search_help" class="sidebar round right" style="text-align:center;">
        <h3><u>Search Help</u></h3>
        <ul>
          <li>Find names, tags, or seeds</li>
          <li>Ages are optional</li>
        </ul>
	  </td>
    </tr>
  </table>
<% else %> 
  <%= redirect_to(root_path) %>
<% end %>

app/views/searches/search.html.erb
<% @user ||= current_user %>

<% @results.each_index do |index| %>
<div id="results">
  <div id="result_name">
    <p>
      <%= link_to "#{@people_results[index].first} #{@people_results[index].last}", 
      		      @people_results[index] %>
    </p>
  </div>
  <div id="result_age">
    <p>
      <%= link_to "#{@results[index].age}", 
      		      @people_results[index] %>
    </p>
  </div>
  <div id="result_story" style="white-space:normal">
    <p>
      <%= link_to "#{@results[index].content}", 
      		      @people_results[index] %>
    </p>
  </div>
</div>
<% end %>


<!--debug search helper.
<h3>Search query: <%= @search.query %></h3>
<h3>Search min_age: <%= @search.min_age %></h3>
<h3>Search max_age: <%= @search.max_age %></h3>

<ul>Name: <%#= link_to result.name, work_path(result) %> - Age - <%#= result.age %></ul>
-->