config/routes.rb
Shapeseed::Application.routes.draw do
  
  resources :user_sessions
  resources :works, :only => [:create, :destroy, :show] do
    member do 
      get :tags
    end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :contributions
  resources :mentorships
  resources :searches
  resources :users do
    member do
      get :following, :followers, :mentors, :contributeds
    end
  end
  resources :people do
    member do
	  get :tags, :works, :mentees, :contributors
	end
  end

  root :to => 'pages#home'
  
  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/signup',    :to => 'users#new'
  match '/relations', :to => 'users#relations'
  match '/suggest',   :to => 'users#suggest'
  match '/contribute', :to => 'people#contribute'
  match 'logout', 	  :to => 'user_sessions#destroy', :as => :logout
  
  match '*path', 	  :to => 'pages#home'
  
  

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
	  <li style="padding: 0 0; float:left; margin-left: 8px;">
	  <% if signed_in? %>
	    <%= link_to "#{current_user.first} #{current_user.last}", relations_path(current_user)%>
	  <% else %>
	    <%= render 'users/user_display' %>
	  <% end %>
	  </li>
	
	  <% if !(@title == "ShapeSeed") %>
        <li><%= link_to "ShapeSeed", root_path %></li>
	  <% end %>
      <li><%= link_to "Suggest", suggest_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign Out", logout_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "raphael.js" %>
    <%= javascript_include_tag "jquery-1.5.2.min.js" %>
    <%= javascript_include_tag "jquery.autocomplete.js" %>
 	<%#=<script type="text/javascript" src="http://use.typekit.com/bmhlptp.js"></script>%>
 	<%#=<script type="text/javascript">try{Typekit.load();}catch(e){}</script>%>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <div id="links">
          <%= render 'layouts/header' %>
        </div>
      </div>
      <div id="content"> 
        <section class="round">
	        <div id="top" class="round">
	          <%= render 'searches/search_bar' %>
	          <div id="userDisplay">
	            <%= render 'users/user_display' %>
	          </div>
	        </div>
          <% flash.each do |key, value| %>
          <div class="flash <%= key %>" style="text-align:center"><%= value %></div>
          <% end %>
          <%= yield %>
          <div id="timeline_display" style="display:none;"></div>
        </section>
      </div>
      <div id="footer">
        <div id="links">
          <%= render 'layouts/footer' %>
        </div>
      </div>
    </div>
  </body>
</html>